[package]
name = "animal_shogi"
version = "0.1.0"
authors = ["mat-der-D <pmahthyemsatics.14or0@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]